### ISSUE TITLE
Where to join?

### ISSUE THREAD

**Issue by blaggacao** [nubark/facturark#5]
Hi @tebanep This is a very valuable initiative! I think I'll drop our internal developments, and join.
Where do you want me to put my hands on, if so?

**Comment by tebanep** [comment]
Hi @blaggacao nice to hear from you again. If you can lend us a hand with the electronic signature, it would be awesome! We are contacting DIAN since a couple of weeks, but they seem to be very busy ;)

Right now, our status is this:

![muisca](https://user-images.githubusercontent.com/6664744/48092588-174fe700-e1db-11e8-862f-01acc50ff56d.png)

Sorry for my late response, I hadn't check the notifications in a while.

**Comment by blaggacao** [comment]
I'll have to get some things finished, yet, and I guess, I can help in in about 2 weeks.

**Comment by tebanep** [comment]
It looks really impressive! Please let me know when you are finished. In the meanwhile, we'll be "coordinating" our development with the DIAN. Think I'll continue with validations as well.

**Comment by tebanep** [comment]
We could finally fix the problem. The library DIAN's service uses for invoice validation is (https://github.com/luisgoncalves/xades4j) and as a Java program (javax.security.auth.x500.X500Principal) it resolves the X509IssuerName in reverse, as specified in RFC2253. Reversing the distinguished names was the trick.

![index](https://user-images.githubusercontent.com/6664744/48848330-a7606580-ed71-11e8-927d-6402601ba079.jpeg)
